title: EuRuKo 2018
description: EuRuKo is the annual European Ruby Conference. Join us in Vienna, Austria on August 24-25, 2018.
show_downloads: false
date_format: "%b %-d, %Y"
github:
  is_project_page: false
theme: jekyll-theme-cayman
sass:
    sass_dir: assets/css/lib
    style: compressed
plugins:
  - jekyll-autoprefixer
