title: EuRuKo 2018
description: The 2018 edition of the European Ruby conference
show_downloads: false
date_format: "%b %-d, %Y"
github:
  is_project_page: false
theme: jekyll-theme-cayman
sass:
    sass_dir: assets/css/lib
    style: compressed
